---
- name: Change the API users passwords (run only once)
  hosts: Wazuh-indexer
  become: true
  become_user: root
  vars_files:
    - ../vars/secrets-development.yml
  tasks:    
    - name: Change API user password (wazuh)
      ansible.builtin.command: "bash wazuh-passwords-tool.sh -au wazuh -ap wazuh -A -u wazuh -p {{ api_password }}"
      args:
        chdir: /usr/share/wazuh-indexer/plugins/opensearch-security/tools/
      notify:
        - Restart wazuh-dashboard
        - Restart wazuh-indexer
        - Restart wazuh-manager
        - Restart filebeat

    - name: Modify Wazuh API configuration
      replace:
        path: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
        regexp: 'word: "wazuh"'
        replace: 'word: "{{ api_password }}"'
      notify:
        - Restart wazuh-dashboard
        - Restart wazuh-indexer
        - Restart wazuh-manager
        - Restart filebeat

    - name: Change API user password (wazuh-wui)
      ansible.builtin.command: "bash wazuh-passwords-tool.sh -au wazuh-wui -ap wazuh-wui -A -u wazuh-wui -p {{ api_wui_password }}"
      args:
        chdir: /usr/share/wazuh-indexer/plugins/opensearch-security/tools/
      notify:
        - Restart wazuh-dashboard
        - Restart wazuh-indexer
        - Restart wazuh-manager
        - Restart filebeat
    
  handlers:
    - name: Restart wazuh-dashboard
      ansible.builtin.service:
        name: wazuh-dashboard
        state: restarted

    - name: Restart wazuh-indexer
      ansible.builtin.service:
        name: wazuh-indexer
        state: restarted

    - name: Restart wazuh-manager
      ansible.builtin.service:
        name: wazuh-manager
        state: restarted

    - name: Restart filebeat
      ansible.builtin.service:
        name: filebeat
        state: restarted
