---
- name: Change dashboard login
  hosts: Wazuh-single
  become: true
  become_user: root
  vars_files:
    - ../vars/secrets-development.yml
  tasks:
    - name: Change dashboard login password (admin)
      ansible.builtin.command: "bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -u admin -p {{ admin_password }} -v"
      notify:
        - Restart wazuh-dashboard
        - Restart wazuh-indexer
        - Restart wazuh-manager
        - Restart filebeat
    
  handlers:
    - name: Restart wazuh-dashboard
      ansible.builtin.service:
        name: wazuh-dashboard
        state: restarted

    - name: Restart wazuh-indexer
      ansible.builtin.service:
        name: wazuh-indexer
        state: restarted

    - name: Restart wazuh-manager
      ansible.builtin.service:
        name: wazuh-manager
        state: restarted

    - name: Restart filebeat
      ansible.builtin.service:
        name: filebeat
        state: restarted
